pip install fuzzywuzzy
pip install pyemd
python generate_train_data.py
python generate_train_data_bigram.py
python generate_tfidf_model_1.py
python generate_tfidf_model_2.py

python ngram.py
python generate_tfidf_feature_1.py
python generate_tfidf_feature_2.py
python generate_feature_cnn.py

python generate_feature_cos_dis_char.py
python generate_feature_cos_dis_word.py
python generate_feature_freq.py
python generate_feature_fuzz.py
python generate_feature_lcs.py
python generate_feature_lcs_sim.py
python generate_feature_token_min_max.py
python generate_feature_word_match.py

python generate_graph_degree_feat.py
python generate_graph_conn_feat.py
